import '../state/app_controller.dart';

class AppLocalizer {
  static const Map<String, Map<String, String>> _texts = {
    'tr': {
      'appTitle': 'Bütçe Takip',
      'login': 'Giriş',
      'register': 'Kayıt Ol',
      'email': 'E-posta',
      'password': 'Şifre',
      'createAccount': 'Hesap Oluştur',
      'welcomeBack': 'Tekrar Hoş Geldin',
      'loginSubtitle': 'Harcamalarını akıllıca yönetmek için giriş yap.',
      'registerSubtitle': 'Yeni hesap oluşturarak bütçeni bugünden takip et.',
      'emailHint': 'örnek@mail.com',
      'passwordHint': 'Şifreni gir',
      'noAccountYet': 'Henüz hesabın yok mu?',
      'haveAccount': 'Zaten hesabın var mı?',
      'signingIn': 'Giriş yapılıyor...',
      'registering': 'Kayıt oluşturuluyor...',
      'registered': 'Kayıt tamam! Giriş yapabilirsin.',
      'dashboard': 'Panel',
      'totalIncome': 'Toplam Gelir',
      'totalExpense': 'Toplam Gider',
      'activeBalance': 'Aktif Param',
      'predictedNextMonth': 'Gelecek Ay Tahmini',
      'categoryBreakdown': 'Kategori Dağılımı',
      'recommendations': 'Öneriler',
      'recentTransactions': 'Son İşlemler',
      'addTransaction': 'İşlem Ekle',
      'income': 'Gelir',
      'amount': 'Tutar',
      'description': 'Açıklama',
      'monthlyIncome': 'Aylık Gelir',
      'monthlyIncomeHint': 'Örn: 45000',
      'monthlyIncomeRequired': 'Aylık gelir 0dan büyük olmalı',
      'accountType': 'Hesap Türü',
      'accountCard': 'Kart',
      'accountCash': 'Nakit',
      'accountIban': 'IBAN',
      'budgetLimits': 'Bütçe Limitleri',
      'budgetLimitsHint':
          'Kategori bazlı aylık limitlerini buradan güncelleyebilirsin.',
      'budgetSaved': 'Bütçe limitleri güncellendi',
      'quickAnalysis': 'Hızlı Analiz',
      'monthChange': 'Bu ay / geçen ay',
      'recurringPayments': 'Fatura & Abonelik',
      'addRecurring': 'Tekrarlayan Ödeme Ekle',
      'dueDay': 'Ödeme Günü',
      'upcomingPayments': 'Yaklaşan Ödemeler',
      'dueInDays': 'kalan gün',
      'invalidRecurringInput': 'Başlık ve tutar alanlarını doğru doldur',
      'exportCsv': 'CSV Dışa Aktar',
      'exportPdf': 'PDF Dışa Aktar',
      'exportSaved': 'Rapor kaydedildi',
      'exportFailed': 'Dışa aktarma başarısız',
      'dataConsentTitle': 'Veri Kullanım Onayı',
      'dataConsentBody':
          'Verilerin, kimlik bilgileri olmadan (anonim) model doğruluğunu artırmak için kullanılmasına izin veriyor musun?',
      'consentAllow': 'İzin Ver',
      'consentDeny': 'İzin Verme',
      'aiPerformance': 'AI Performansı',
      'totalTrainingSamples': 'Toplam Eğitim Örneği',
      'correctedSamples': 'Düzeltilen Örnek',
      'uniqueCategories': 'Benzersiz Kategori',
      'validationAccuracy': 'Doğrulama Doğruluğu',
      'lastRetrainAt': 'Son Yeniden Eğitim',
      'lastRetrainSamples': 'Son Eğitim Örnek Sayısı',
      'datasetSources': 'Veri Kaynakları',
      'perCategoryDistribution': 'Kategori Dağılımı',
      'thesisSummary': 'Tez Özeti',
      'weeklyAnalysis': 'Haftalık Analiz',
      'last7Days': 'Son 7 gün',
      'previous7Days': 'Önceki 7 gün',
      'weeklyChange': 'Haftalık değişim',
      'aiDataConsent': 'AI Veri Kullanım İzni',
      'aiCoach': 'AI Koç',
      'coachHint': 'Örn: bunu 3500 TL ye alsam ne olur?',
      'onboardingTitle': 'Başlangıç Kurulumu',
      'onboardingSubtitle': '3 adımda kişisel planını oluşturalım.',
      'onboardingStepIncome': 'Gelir',
      'onboardingStepEssentials': 'Temel Gider',
      'onboardingStepGoal': 'Birikim Hedefi',
      'essentialExpense': 'Aylık Temel Gider',
      'essentialExpenseHint': 'Örn: kira + faturalar toplamı',
      'savingsGoal': 'Aylık Birikim Hedefi',
      'savingsGoalHint': 'Örn: 5000',
      'continueNext': 'Devam',
      'finishSetup': 'Kurulumu Bitir',
      'back': 'Geri',
      'categoryOptional': 'Kategori (opsiyonel)',
      'categorySelect': 'Kategori',
      'incomeCategorySelect': 'Gelir Kategorisi',
      'expenseCategorySelect': 'Gider Kategorisi',
      'autoCategory': 'Otomatik (Model seçsin)',
      'food': 'Yemek',
      'market': 'Market',
      'transport': 'Ulaşım',
      'bills': 'Faturalar',
      'entertainment': 'Eğlence',
      'other': 'Diğer',
      'salary': 'Maaş',
      'additionalIncome': 'Ek Gelir',
      'scholarship': 'Burs',
      'freelance': 'Freelance',
      'investment': 'Yatırım Getirisi',
      'rentalIncome': 'Kira Geliri',
      'giftIncome': 'Hediye/Nakit',
      'otherIncome': 'Diğer Gelir',
      'generalIncome': 'Genel Gelir',
      'pickDate': 'Tarih Seç',
      'date': 'Tarih',
      'save': 'Kaydet',
      'saving': 'Kaydediliyor...',
      'settings': 'Ayarlar',
      'profile': 'Profil',
      'profileSaved': 'Profil güncellendi',
      'monthlyTarget': 'Aylık Gelir Hedefi',
      'language': 'Dil',
      'theme': 'Tema',
      'currency': 'Para Birimi',
      'financialReminders': 'Bütçe Hatırlatmaları',
      'financialRemindersHint': 'Beş günde bir bütçe durum bildirimi al.',
      'darkMode': 'Karanlık Mod',
      'lightMode': 'Açık Mod',
      'systemMode': 'Sistem',
      'turkish': 'Türkçe',
      'english': 'İngilizce',
      'missingToken': 'Token bulunamadı',
      'amountNonZero': 'Tutar sıfır olamaz',
      'logout': 'Çıkış',
      'menu': 'Menü',
      'home': 'Ana Sayfa',
      'categories': 'Kategoriler',
      'categoryDetails': 'Kategori Detayları',
      'exchangeRates': 'Döviz Kuru',
      'noCategoryData': 'Henüz kategori verisi yok.',
      'noTransactions': 'Henüz işlem yok.',
      'refresh': 'Yenile',
      'retry': 'Tekrar Dene',
      'baseCurrency': 'Baz Para Birimi',
      'amountToConvert': 'Dönüştürülecek Tutar',
      'conversionResult': 'Dönüşüm Sonucu',
      'updatedNow': 'Güncellendi',
      'fxError': 'Döviz verisi alınamadı',
      'viewAllRates': 'Tüm Kurları Gör',
      'convert': 'Dönüştür',
      'financialTools': 'Finans Araçları',
      'records': 'Kayıtlar',
      'incomeList': 'Gelirler',
      'expenseList': 'Giderler',
      'search': 'Ara',
      'filter': 'Filtre',
      'clear': 'Temizle',
      'apply': 'Uygula',
      'fromDate': 'Başlangıç Tarihi',
      'toDate': 'Bitiş Tarihi',
      'minAmount': 'Min Tutar',
      'maxAmount': 'Max Tutar',
      'allCategories': 'Tüm Kategoriler',
      'monthlyReport': 'Aylık Rapor',
      'about': 'Hakkında',
      'aboutSubtitle': 'Uygulama Bilgileri',
      'total': 'Toplam',
      'month': 'Ay',
      'incomeVsExpense': 'Gelir ve Gider Karşılaştırması',
      'net': 'Net',
      'positiveNet': 'Pozitif',
      'negativeNet': 'Negatif',
      'lastUpdated': 'Son güncelleme',
      'investments': 'Yatırım Araçları',
      'liveMarketData': 'Canlı Piyasa Verisi',
      'marketDataError': 'Piyasa verisi alınamadı',
      'change24h': '24s Değişim',
      'price': 'Fiyat',
      'coins': 'Coinler',
      'coinMarket': 'Kripto Piyasası',
      'investmentAssets': 'Yatırım Araçları',
      'assetsMarket': 'Emtia ve Endeksler',
      'portfolio': 'Portföy',
      'portfolioAdd': 'Ekle',
      'portfolioEdit': 'Düzenle',
      'portfolioPin': 'Sabitle/Favori',
      'portfolioQuantity': 'Miktar',
      'portfolioAvgPrice': 'Ortalama Alış',
      'portfolioPositionExists': 'Portföyde var',
      'portfolioInvalidInput': 'Geçerli miktar ve fiyat gir',
      'portfolioAddInvestment': 'Yatırım Ekle',
      'portfolioAsset': 'Varlık',
      'portfolioSummary': 'Toplam Portföy',
      'portfolioTotalInvested': 'Toplam Yatırılan',
      'portfolioCurrentValue': 'Güncel Değer',
      'portfolioPnl': 'Kâr/Zarar',
      'portfolioEmpty':
          'Henüz portföye varlık eklenmedi. Sağ alttaki + ile ekleyebilirsin.',
      'alerts': 'Alarmlar',
      'noAlerts': 'Kayıtlı alarm yok.',
      'alertAbove': 'Üstüne çıkarsa',
      'alertBelow': 'Altına düşerse',
      'active': 'Aktif',
      'inactive': 'Pasif',
      'editAlert': 'Alarmı düzenle',
      'deleteAlert': 'Alarmı sil',
    },
    'en': {
      'appTitle': 'Budget Tracker',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'createAccount': 'Create account',
      'welcomeBack': 'Welcome Back',
      'loginSubtitle': 'Sign in to manage your budget smarter.',
      'registerSubtitle': 'Create an account and start tracking today.',
      'emailHint': 'name@mail.com',
      'passwordHint': 'Enter your password',
      'noAccountYet': 'Do not have an account yet?',
      'haveAccount': 'Already have an account?',
      'signingIn': 'Signing in...',
      'registering': 'Registering...',
      'registered': 'Registered! Please login.',
      'dashboard': 'Dashboard',
      'totalIncome': 'Total Income',
      'totalExpense': 'Total Expense',
      'activeBalance': 'Active Balance',
      'predictedNextMonth': 'Predicted Next Month',
      'categoryBreakdown': 'Category Breakdown',
      'recommendations': 'Recommendations',
      'recentTransactions': 'Recent Transactions',
      'addTransaction': 'Add Transaction',
      'income': 'Income',
      'amount': 'Amount',
      'description': 'Description',
      'monthlyIncome': 'Monthly Income',
      'monthlyIncomeHint': 'e.g. 1500',
      'monthlyIncomeRequired': 'Monthly income must be greater than 0',
      'accountType': 'Account Type',
      'accountCard': 'Card',
      'accountCash': 'Cash',
      'accountIban': 'IBAN',
      'budgetLimits': 'Budget Limits',
      'budgetLimitsHint': 'Update your monthly category limits here.',
      'budgetSaved': 'Budget limits updated',
      'quickAnalysis': 'Quick Analysis',
      'monthChange': 'This month / last month',
      'recurringPayments': 'Recurring Payments',
      'addRecurring': 'Add Recurring Payment',
      'dueDay': 'Due Day',
      'upcomingPayments': 'Upcoming Payments',
      'dueInDays': 'days left',
      'invalidRecurringInput': 'Please enter a valid title and amount',
      'exportCsv': 'Export CSV',
      'exportPdf': 'Export PDF',
      'exportSaved': 'Report saved',
      'exportFailed': 'Export failed',
      'dataConsentTitle': 'Data Consent',
      'dataConsentBody':
          'Do you allow your anonymized data to be used to improve model accuracy?',
      'consentAllow': 'Allow',
      'consentDeny': 'Deny',
      'aiPerformance': 'AI Performance',
      'totalTrainingSamples': 'Total Training Samples',
      'correctedSamples': 'Corrected Samples',
      'uniqueCategories': 'Unique Categories',
      'validationAccuracy': 'Validation Accuracy',
      'lastRetrainAt': 'Last Retrain',
      'lastRetrainSamples': 'Last Retrain Samples',
      'datasetSources': 'Dataset Sources',
      'perCategoryDistribution': 'Category Distribution',
      'thesisSummary': 'Thesis Summary',
      'weeklyAnalysis': 'Weekly Analysis',
      'last7Days': 'Last 7 days',
      'previous7Days': 'Previous 7 days',
      'weeklyChange': 'Weekly change',
      'aiDataConsent': 'AI Data Consent',
      'aiCoach': 'AI Coach',
      'coachHint': 'e.g. what if I buy this for 3500?',
      'onboardingTitle': 'Initial Setup',
      'onboardingSubtitle': 'Create your personal plan in 3 steps.',
      'onboardingStepIncome': 'Income',
      'onboardingStepEssentials': 'Essentials',
      'onboardingStepGoal': 'Savings Goal',
      'essentialExpense': 'Monthly Essential Expense',
      'essentialExpenseHint': 'e.g. rent + bills total',
      'savingsGoal': 'Monthly Savings Goal',
      'savingsGoalHint': 'e.g. 200',
      'continueNext': 'Continue',
      'finishSetup': 'Finish Setup',
      'back': 'Back',
      'categoryOptional': 'Category (optional)',
      'categorySelect': 'Category',
      'incomeCategorySelect': 'Income Category',
      'expenseCategorySelect': 'Expense Category',
      'autoCategory': 'Auto (Use model)',
      'food': 'Food',
      'market': 'Market',
      'transport': 'Transport',
      'bills': 'Bills',
      'entertainment': 'Entertainment',
      'other': 'Other',
      'salary': 'Salary',
      'additionalIncome': 'Additional Income',
      'scholarship': 'Scholarship',
      'freelance': 'Freelance',
      'investment': 'Investment Return',
      'rentalIncome': 'Rental Income',
      'giftIncome': 'Gift/Cash',
      'otherIncome': 'Other Income',
      'generalIncome': 'General Income',
      'pickDate': 'Pick date',
      'date': 'Date',
      'save': 'Save',
      'saving': 'Saving...',
      'settings': 'Settings',
      'profile': 'Profile',
      'profileSaved': 'Profile updated',
      'monthlyTarget': 'Monthly Income Target',
      'language': 'Language',
      'theme': 'Theme',
      'currency': 'Currency',
      'financialReminders': 'Budget Reminders',
      'financialRemindersHint':
          'Get a budget status notification every five days.',
      'darkMode': 'Dark',
      'lightMode': 'Light',
      'systemMode': 'System',
      'turkish': 'Turkish',
      'english': 'English',
      'missingToken': 'Missing token',
      'amountNonZero': 'Amount must be non-zero',
      'logout': 'Logout',
      'menu': 'Menu',
      'home': 'Home',
      'categories': 'Categories',
      'categoryDetails': 'Category Details',
      'exchangeRates': 'Exchange Rates',
      'noCategoryData': 'No category data yet.',
      'noTransactions': 'No transactions yet.',
      'refresh': 'Refresh',
      'retry': 'Retry',
      'baseCurrency': 'Base Currency',
      'amountToConvert': 'Amount to Convert',
      'conversionResult': 'Conversion Result',
      'updatedNow': 'Updated',
      'fxError': 'Failed to fetch exchange rates',
      'viewAllRates': 'View All Rates',
      'convert': 'Convert',
      'financialTools': 'Financial Tools',
      'records': 'Records',
      'incomeList': 'Incomes',
      'expenseList': 'Expenses',
      'search': 'Search',
      'filter': 'Filter',
      'clear': 'Clear',
      'apply': 'Apply',
      'fromDate': 'From Date',
      'toDate': 'To Date',
      'minAmount': 'Min Amount',
      'maxAmount': 'Max Amount',
      'allCategories': 'All Categories',
      'monthlyReport': 'Monthly Report',
      'about': 'About',
      'aboutSubtitle': 'Application Info',
      'total': 'Total',
      'month': 'Month',
      'incomeVsExpense': 'Income vs Expense',
      'net': 'Net',
      'positiveNet': 'Positive',
      'negativeNet': 'Negative',
      'lastUpdated': 'Last updated',
      'investments': 'Investments',
      'liveMarketData': 'Live Market Data',
      'marketDataError': 'Failed to fetch market data',
      'change24h': '24h Change',
      'price': 'Price',
      'coins': 'Coins',
      'coinMarket': 'Crypto Market',
      'investmentAssets': 'Investment Assets',
      'assetsMarket': 'Commodities and Indices',
      'portfolio': 'Portfolio',
      'portfolioAdd': 'Add',
      'portfolioEdit': 'Edit',
      'portfolioPin': 'Pin/Favorite',
      'portfolioQuantity': 'Quantity',
      'portfolioAvgPrice': 'Average Buy Price',
      'portfolioPositionExists': 'In portfolio',
      'portfolioInvalidInput': 'Enter a valid quantity and price',
      'portfolioAddInvestment': 'Add Investment',
      'portfolioAsset': 'Asset',
      'portfolioSummary': 'Portfolio Summary',
      'portfolioTotalInvested': 'Total Invested',
      'portfolioCurrentValue': 'Current Value',
      'portfolioPnl': 'Profit/Loss',
      'portfolioEmpty':
          'No portfolio assets yet. Use + at bottom right to add.',
      'alerts': 'Alerts',
      'noAlerts': 'No alerts yet.',
      'alertAbove': 'When above',
      'alertBelow': 'When below',
      'active': 'Active',
      'inactive': 'Inactive',
      'editAlert': 'Edit alert',
      'deleteAlert': 'Delete alert',
    }
  };

  static String text(AppController controller, String key) {
    final lang = controller.settings.languageCode;
    return _texts[lang]?[key] ?? _texts['en']![key] ?? key;
  }
}
